---
Title: Contas
Weight: 70
---

= Contas

O módulo Contas é a base centralizada a partir da qual você pode criar uma associação com a maioria dos registros no SuiteCRM. É possível criar um relacionamento com Contatos, Leads convertidos, Oportunidades, qualquer Atividade como E-mails ou Reuniões e Casos. As contas no SuiteCRM geralmente contêm todas as informações específicas de uma empresa com a qual sua organização se relacionará. Em termos do mundo real, uma conta pode ser uma entidade comercial que seja uma perspectiva de vendas qualificada, cliente, fornecedor ou revendedor e pode ser usada para rastrear todas as interações que ocorrem entre essas entidades e sua organização.

== Ações de Contas

Você pode acessar as ações de contas no menu suspenso do módulo de contas ou na barra lateral. As ações de contas são as seguintes:

* *Criar conta* – Depois de clicado, um novo formulário é aberto em Editar visualização para permitir que você crie um novo registro de conta.
* *Ver contas * – Uma vez clicado, você será redirecionado para a visualização de lista para o módulo Contas. Isso permite pesquisar e listar registros de contas.
* *Importar Contas* – redireciona você para o Assistente de Importação para o módulo Contas. Para mais informações, consulte  link:/user/introduction/user-interface/#_importing_records[Importando Registros].

To view the full list of fields available when creating an Account, See
link:/user/appendix-a/#_accounts_field_list[Accounts Field List].

== Managing Accounts

* To sort records on the Accounts List View, click any column title
which is sortable. This will sort the column either ascending or
descending.
* To search for a Account, see the link:/user/introduction/user-interface/#_search[Search] section of this
user guide.
* To update some or all the Accounts on the List View, use the Mass
Update panel as described in the link:/user/introduction/user-interface/#_mass_updating_records[Mass Updating Records] section of this user guide.
* To duplicate a Account, you can click the Duplicate button on the
Detail View and then save the duplicate record.
* To merge duplicate Accounts, select the records from the Accounts List
View, click the Merge link in the Actions drop-down list, and progress
through the merge process. For more information on Merging Duplicates,
see the link:/user/introduction/user-interface/#_merging_records[Merging Records] section of this user
guide.
* To delete one or multiple Accounts, you can select multiple records
from the List View and click delete. you can also delete a Account from
the Detail View by clicking the Delete button. For a more detailed guide
on deleting records, see the link:/user/introduction/user-interface/#_deleting_records[Deleting Records]
section of this user guide.
* To view the details of a Account, click the Account Name in the List
View. This will open the record in Detail View.
* To edit the Account details, click Edit icon within the List View or
click the edit button on the Detail View, make the necessary changes,
and click Save.
* For a detailed guide on importing and exporting Accounts, see the
link:/user/introduction/user-interface/#_importing_records[Importing Records] and
link:/user/introduction/user-interface/#_exporting_records[Exporting Records] sections of this user guide.
* To track all changes to audited fields, in the Account record, you can
click the View Change Log button on the Account's Detail View or Edit
View.
